name: "Test"

on: 
  pull_request:
    branches:
      - main

jobs:
  apply:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -v
      - name: Check Syntax
        run: terraform fmt -check -recursive -diff
